name: Test Unit

on:
    pull_request:

env:
  # Install packages into system environment.
  # Follows: https://docs.astral.sh/uv/guides/integration/github/#using-uv-pip
  UV_SYSTEM_PYTHON: 1

jobs:
    test-unit:
        name: Test Unit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up uv
              uses: astral-sh/uv-action@v5
              with:
                  python-version: 3.11
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: >
                make install
            - name: Run tests
              run: >
                make test